### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by MrCl0wnLab** [MrCl0wnLab/WP-AFD-Checker#1]
**Organizar class afdrequest**
- [ ] Criar propriedade que gera user-agent random
- [ ] Criar propriedade para tratar retorno code http
- [ ] Criar atributo para setar user-agent
- [ ] Criar atributo para setar header
- [ ] Criar atributo para setar timeout

**Argumentos CMD**
- [ ] Criar parâmetros de fuzzing
- [ ] Criar parâmetro para update do arquivo inject.csv
- [ ] Criar parâmetro para update de código
- [ ] Criar parâmetro para help

**Tunning**
- [ ] Implementação de multithread

**Output de resultado**
- [ ] Criar class focada no gerenciamento e formatação de resultados

**Documentação**
- [ ]  Git
- [ ]  Code
